name: RapidForce Builder

on:
  push:
    branches:
      - master
      - feature/ci

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build the solution
      run: msbuild RapidForce.sln
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: resources
        path: resources/